# Generated by Django 4.2.16 on 2024-11-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('areaOfCompetition', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamId', models.IntegerField()),
                ('name', models.CharField(max_length=25, null=True)),
                ('founded', models.IntegerField(default=0, null=True)),
                ('venue', models.CharField(max_length=25, null=True)),
                ('coachName', models.CharField(default='', max_length=40, null=True)),
                ('squad', models.JSONField(default=dict, null=True)),
                ('competitionCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fdbAPI.competitions', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonStage', models.CharField(max_length=25)),
                ('teamId', models.IntegerField()),
                ('teamName', models.CharField(max_length=25, null=True)),
                ('position', models.IntegerField()),
                ('playedGames', models.IntegerField()),
                ('gamesWon', models.IntegerField()),
                ('gamesDrawn', models.IntegerField()),
                ('gamesLost', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goalsFor', models.IntegerField()),
                ('goalsAgainst', models.IntegerField()),
                ('competitionCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fdbAPI.competitions', to_field='code')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.IntegerField()),
                ('matchDateUTC', models.DateTimeField()),
                ('updateDate', models.DateTimeField()),
                ('homeTeamId', models.IntegerField(null=True)),
                ('homeTeamName', models.CharField(max_length=25, null=True)),
                ('awayTeamId', models.IntegerField(null=True)),
                ('awayTeamName', models.CharField(max_length=25, null=True)),
                ('winner', models.CharField(max_length=25, null=True)),
                ('halfTimeHomeGoals', models.IntegerField(null=True)),
                ('halfTimeAwayGoals', models.IntegerField(null=True)),
                ('fullTimeHomeGoals', models.IntegerField(null=True)),
                ('fullTimeAwayGoals', models.IntegerField(null=True)),
                ('competitionCode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fdbAPI.competitions', to_field='code')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teams',
            constraint=models.UniqueConstraint(fields=('competitionCode', 'teamId'), name='unique_competition_id'),
        ),
        migrations.AddConstraint(
            model_name='standings',
            constraint=models.UniqueConstraint(fields=('competitionCode', 'seasonStage', 'teamId'), name='unique_competition_seasonStage_teamId'),
        ),
    ]
